languageCode = "ko-KR"
title = "My Technical Romance"
baseURL = "https://zeushin.github.io/"
theme = "ghostwriter"
copyright = "Masher Shin"
publishdir = "dist"
disqusShortname = "zeushin"

[Author]
    name = "Masher"
    profile = "https://github.com/zeushin"

[Taxonomies]
    tag = "tags"

[Params]
    intro = true
    dateFormat = "Mon, Jan 2, 2006"
    github = "https://github.com/zeushin"
    linkedin = "https://www.linkedin.com/in/bumcheol-shin-a7267154/"
    twitter = "https://twitter.com/masher_s"
    email = "zeushin@gmail.com"

[Permalinks]
    post = "/:year/:month/:day/:filename/"

[[menu.main]]
    name = "Blog"
    url = "/"
    weight = 1

# [[menu.main]]
#     name = "Projects"
#     url = "/project/"
#     weight = 2

# [[menu.main]]
#     name = "Contact"
#     url = "/page/contact/"
#     weight = 3

[[menu.main]]
    name = "About"
    url = "/page/about/"
    weight = 2